// This contains definitions that specify the physics choices for this problem
// Parameters defined here are:
// PROPMODEL -- specifies the microphysical CR propagation model to use
// LOSSMODEL -- specifies the model to use to describe CR losses
// UNITS -- specifies whether to use MKS or CGS units for grid quantities

#define PROPMODEL       POWERLAW
#define LOSSMODEL       NONE
#define UNITS           CGS

